name: Build Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy JAR to packaging
        run: |
          mkdir -p packaging/windows/out
          Copy-Item -Path build/libs/*.jar -Destination packaging/windows/out/ -Force

      - name: Download and extract Launch4j
        run: |
          curl -L -o launch4j.zip https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-win32.zip/download
          7z x launch4j.zip
        shell: cmd

      - name: Run Launch4j
        run: |
          .\launch4j\launch4j.exe packaging\windows\launch4j.xml
        shell: cmd

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build Installer with Inno Setup
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" packaging\windows\installer.iss'
        shell: cmd

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: MCSRLauncherInstaller
          path: |
            packaging\windows\Output\*.exe
            build/libs/*.jar