name: Build and Release Installer

on:
  push:
    tags:
      - '*'

jobs:
  build-release:
    runs-on: windows-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.id }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy JAR to packaging
        run: |
          mkdir -p packaging/windows/out
          Copy-Item -Path build/libs/*.jar -Destination packaging/windows/out/ -Force
        shell: pwsh

      - name: Download and extract Launch4j
        run: |
          curl -L -o launch4j.zip https://sourceforge.net/projects/launch4j/files/launch4j-3/3.50/launch4j-3.50-win32.zip/download
          7z x launch4j.zip
        shell: cmd

      - name: Run Launch4j
        run: |
          set LAUNCH4J_XML=%CD%\packaging\windows\launch4j.xml
          .\launch4j\launch4j.exe "%LAUNCH4J_XML%"
        shell: cmd

      - name: Install Inno Setup
        run: choco install innosetup -y
        shell: pwsh

      - name: Build Installer with Inno Setup
        run: '"C:\Program Files (x86)\Inno Setup 6\ISCC.exe" packaging\windows\installer.iss'
        shell: cmd

      - name: Generate Changelog
        id: changelog
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^)
          echo "Previous tag: $PREV_TAG"
          echo "Changelog:"
          git log $PREV_TAG..HEAD --pretty=format:"- %s" > changelog.txt
          cat changelog.txt
          echo "::set-output name=body::$(cat changelog.txt | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g')"
        shell: bash

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.body }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packaging/windows/Output/*.exe
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
